spring.application.name=demo

spring.datasource.url=jdbc:postgresql://localhost:5432/jwtdb
spring.datasource.username=jwt_user
spring.datasource.password=changeMe123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql

spring.jpa.hibernate.ddl-auto=none

app.jwt.secret=REPLACE_ME_WITH_A_LONG_RANDOM_256bit_SECRET
app.jwt.access-exp-ms=900000
app.jwt.refresh-exp-ms=604800000
